version: "3"
services:
  web:
    build:
      context: web
      target: prepare
      dockerfile: Dockerfile.local
    command: >
      bash -c "yarn install && yarn run dev-docker"
    volumes:
      - "./web/app:/svelte_app"
      - "web_node_modules:/svelte_app/node_modules"
    ports:
      - "5173:5173"

  backend:
    build:
      context: server/app
      target: prepare
      dockerfile: Dockerfile.local
    volumes:
      - "./server/app:/server"
      - "backend_node_modules:/server/node_modules"
    command: >
      bash -c "yarn install && yarn run start"
    ports:
      - "3000:3000"

  database:
    ports:
      - "5432:5432"
volumes:
  web_node_modules:
  backend_node_modules:
