version: '3'
services:
  web:
    build:
      context: web
      target: develop
      dockerfile: Dockerfile.local
    ports:
      - "8080:80"

  backend:
    build:
      context: server/app
      target: develop
      dockerfile: Dockerfile.local

    ports:
      - "3000:3000"


