version: '3'
services:
  web:
    build:
      context: web
      target: develop
      dockerfile: Dockerfile.local
    command: yarn run dev --host
    ports:
      - "5173:5173"

  backend:
    build:
      context: server/app
      target: develop
      dockerfile: Dockerfile.local
    command: yarn run start
    ports:
      - "3000:3000"


