version: '3'
services:
  web:
    build: web
    container_name: baba_web
    ports:
      - "8080:80"
  backend:
    build: server/app
    container_name: baba_backend
    ports:
      - "3000:3000"
  database:
    image: postgres:15.1-alpine
    container_name: baba_database
