version: '3'
services:
  web:
    build: web
    container_name: baba_web
    ports:
      - "80:80"
    networks:
      - web

  backend:
    build: server/app
    container_name: baba_backend
    networks:
      - web
      - server

  database:
    image: postgres:15.1-alpine
    container_name: baba_database
    networks:
      - server

networks:
  web:
    driver: bridge
  server:
    driver: bridge
