version: '3'
services:
  web:
    build: web
    container_name: baba_web
    environment:
      TZ: ${TZ}
    ports:
      - "80:80"
    networks:
      - web

  backend:
    build: server/app
    container_name: baba_backend
    environment:
      TZ: ${TZ}
    networks:
      - web
      - server
    depends_on:
      - database

  database:
    image: postgres:15.1-alpine
    container_name: baba_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
    ports:
      - 5432:5432
    networks:
      - server

networks:
  web:
    driver: bridge
  server:
    driver: bridge
