name: web container build test

on:
  push:
    paths:
      - "web/**"
      - ".github/workflows/web_container.yml"
  pull_request:
    types: [opened, reopened, synchronize, review_requested]
    paths:
      - "web/**"
      - ".github/workflows/web_container.yml"

defaults:
  run:
    working-directory: web

jobs:
  container:
    runs-on: ubuntu-latest
    if: >-
      ${{
        github.event_name == 'pull_request' &&
        github.event.action != 'synchronize' ||
        github.run_attempt != 1
      }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Build local container
        run: docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile.local .
      - name: Build product container
        run: docker buildx build --platform linux/amd64,linux/arm64 .
