# prepare svelte project
# make,python3,g++ -> node-gyp required
FROM node:16.6.1-slim AS prepare
WORKDIR /svelte_app
ENV LIB="git curl wget make python3 g++"
RUN apt update \
  && apt install -y $LIB --no-install-recommends

# build svelte app
FROM prepare AS builder
COPY app/public ./public
RUN yarn install
COPY app ./
RUN yarn build

# nginx(product)
FROM nginx:stable AS product
WORKDIR /var/www/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /svelte_app/dist ./

